use_frameworks!
platform :ios, '8.0'

target 'XCoordinator_Example' do
  pod 'XCoordinator', :path => '../'
  pod 'XCoordinator/RxSwift', :path => '../'
  pod 'Action', '~> 3.9'
  pod 'SwiftLint'

  target 'XCoordinator_Tests' do
    inherit! :search_paths
  end
end
