use_frameworks!
platform :ios, '8.0'

target 'XCoordinator_Example' do
  pod 'XCoordinator', :path => '../'
  pod 'XCoordinator/RxSwift', :path => '../'
  pod 'Action', '~> 4.0', :inhibit_warnings => true
  pod 'RxSwift', '~> 5.0', :inhibit_warnings => true
  pod 'RxCocoa', '~> 5.0', :inhibit_warnings => true
  pod 'SwiftLint'

  target 'XCoordinator_Tests' do
    inherit! :search_paths
  end
end
