# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XCoordinator-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCoordinator-Example
  pod 'XCoordinator', :path => '../'
  pod 'XCoordinator/RxSwift', :path => '../'
  pod 'Action'

  target 'XCoordinator-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
