# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxCoordinator-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxCoordinator-Example
  pod 'rx-coordinator', :path => '../'
  pod 'rx-coordinator/RxSwift', :path => '../'
  pod 'Action'

  target 'RxCoordinator-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
