name: Publish documentation

on:
  push:
    tags: ["*"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build documentation
        run: |
          swift package \
            --allow-writing-to-directory ./Documentation \
            generate-documentation \
            --target XCoordinator \
            --output-path ./Documentation \
            --transform-for-static-hosting \
            --hosting-base-path XCoordinator \
            --warnings-as-errors

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Documentation

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
