name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean build -scheme XCoordinator
    - name: Run tests
      run: xcodebuild test -scheme XCoordinator
