name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild -scheme XCoordinator clean build
    - name: Run tests
      run: xcodebuild -scheme XCoordinator test
