name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift package generate-xcodeproj && xcodebuild -project XCoordinator.xcodeproj
    - name: Run tests
      run: xcodebuild test -project XCoordinator.xcodeproj
